dist: xenial
language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
install:
  - python setup.py install
  - pip install pytest-cov pytest-django mock
script:
  - pytest --cov-config .coveragerc --cov=pyas2lib
after_success:
  - pip install codecov
  - codecov
